# Generated by Django 5.2.6 on 2025-11-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_fetching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='weather_code',
        ),
    ]
